# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: Python36\python setup.py build
  displayName: 'Python to C'

- script: |
    set PATH=MinGW\bin\;%PATH%;MinGW\usr\include\python3.6m\
    MinGW\bin\x86_64-pc-cygwin-gcc-7.4.0.exe run.c -I MinGW\bin -I MinGW\usr\include\python3.6m\ -I CryptLib\ -lpython3.6m -L MinGW/usr/include/python3.6/ -o PFSA.exe'
  displayName: 'C to .exe file'
