# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: Python36\python setup.py
  displayName: 'Python to C'

- script: |
    set PATH=%PATH%;MinGW\bin\
    MinGW\bin\gcc run.c -o PFSA.exe
  displayName: 'C to .exe file'
